### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/isort-ts#2]
Partially copied from https://github.com/hi-ogawa/jscodeshift-isort/issues/2

- [x] archive https://github.com/hi-ogawa/jscodeshift-isort
- [ ] testing
  - [ ] collect test cases from somewhere
    - type import, default import, star import, import assersion
    - multiple sections
    - preserve comment and new lines
  - [ ] use it on personal projects
    - https://github.com/hi-ogawa/unocss-preset-antd/pull/17
    - https://github.com/hi-ogawa/web-ext-tab-manager/pull/17
- [x] standalone cli improvement
  - [x] use cac, consola, etc...
  - [x] cache https://github.com/hi-ogawa/isort-ts/compare/feat-cli-cache?expand=1
  - [x] git based file gathering https://github.com/hi-ogawa/isort-ts/pull/5
  - [ ] test
- [x] customize-able order https://github.com/hi-ogawa/isort-ts/pull/10
  - https://github.com/trivago/prettier-plugin-sort-imports/blob/8d191fc9be85f20ff742456a333858f92ffdd860/src/index.ts#L9
  - https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md
  - [x] detect builtin? https://github.com/import-js/eslint-plugin-import/blob/d5fc8b670dc8e6903dbb7b0894452f60c03089f5/src/core/importType.js#L30
    - https://github.com/hi-ogawa/isort-ts/pull/4
  - [x] eslint compat default 
    - https://github.com/hi-ogawa/isort-ts/pull/7
- [ ] maybe try to preserve comment/trivia as a best effort

<details><summary>currently comments are fixed between imports</summary>

https://github.com/hi-ogawa/isort-ts/blob/02ac9e41c54fac8bdaafe9711024990f5c964f95/src/transformer.test.ts#L87-L103

</details>

**Comment by hi-ogawa** [comment]
Looks fine for the time being.
